# Site settings
title: "CS371p Fall 2015: Lane Kolbly"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Website for CS371P, Object Oriented Programming
baseurl: "/cs371p-web" # the subpath of your site, e.g. /blog/
url: "http://lkolbly.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_image_url: /lane.jpg
      header_image_caption: "This is an image of me doing what I do when I'm not at a computer."

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
